// Catálogo do Socially Savvy: 110 habilidades em 7 áreas do desenvolvimento
// social, transcritas da planilha Planilhas/SOCIALLY--SAVVY-PEI.xlsx que a
// clínica preenchia à mão. Fixo em código, como lib/fono-instruments/ — não é
// cadastrável pelo gestor, ao contrário de protocols/protocol_items.
//
// Cada habilidade é pontuada de 0 a 3 (ou "NA", não avaliada) por aplicação.
// Os códigos (JA01, SP01, ...) são os da planilha e são a chave estável das
// respostas gravadas em socially_savvy_assessments.responses.

import type { SociallySavvyArea } from "./types";

export const SOCIALLY_SAVVY_CATALOG: SociallySavvyArea[] = [
  {
    key: "ja",
    label: "Atenção Compartilhada",
    items: [
      { code: "JA01", text: "Orienta-se (ex: olha ou faz uma resposta relacionada) quando um objeto é apresentado" },
      { code: "JA02", text: "Repete seu próprio comportamento para manter a interação social" },
      { code: "JA03", text: "Repete ação com brinquedo para manter a interação social" },
      { code: "JA04", text: "Usa o olhar fixo para manter a interação social (ou seja, olha diretamente para o rosto da outra pessoa por pelo menos um segundo várias vezes ao longo da interação)" },
      { code: "JA05", text: "Segue o apontar ou gesto para objetos" },
      { code: "JA06", text: "Segue o olhar para objetos" },
      { code: "JA07", text: "Mostra objetos aos outros e faz contato visual para compartilhar interesse" },
      { code: "JA08", text: "Aponta para objetos e faz contato visual para compartilhar interesse" },
      { code: "JA09", text: "Comenta sobre o que ele mesmo ou os outros estão fazendo (por exemplo, \"Eu estou (ação)\".)" },
    ],
  },
  {
    key: "sp",
    label: "Brincar Social",
    items: [
      { code: "SP01", text: "Envolve-se em jogos interativos sociais (por exemplo, Peek-a-Boo, jogo de cócegas)" },
      { code: "SP02", text: "Brinca em paralelo por cinco a dez minutos, próximo a pares com brinquedos de final definido (por exemplo, quebra-cabeças, classificadores de formas)" },
      { code: "SP03", text: "Brinca paralelamente de cinco a dez minutos, perto de pares com brinquedos de uso livre (por exemplo, blocos, caminhões, LEGOs)" },
      { code: "SP04", text: "Compartilha brinquedos / materiais (por exemplo, permite que outros brinquem com materiais, fornece materiais quando solicitado)" },
      { code: "SP05", text: "Brinca cooperativamente (dá e recebe instruções de pares) por cinco a dez minutos com brinquedos próximos (puzzles, classificadores de formas)" },
      { code: "SP06", text: "Brinca cooperativamente (dá e recebe instruções de pares) por cinco a dez minutos com brinquedos abertos (por exemplo, blocos, caminhões, LEGOs)" },
      { code: "SP07", text: "Alterna o turno como parte de um jogo estruturado e mantém a atenção até a conclusão do jogo" },
      { code: "SP08", text: "Executa jogos ao ar livre com um grupo até a conclusão da atividade (por exemplo, gato e rato, queimada)" },
      { code: "SP09", text: "Para a ação quando solicitado por um par" },
      { code: "SP10", text: "Termina a brincadeira/ jogo estruturado com o par apropriadamente" },
      { code: "SP11", text: "Desempenha um papel em um tema de jogo imaginativo e o sustenta, verbalmente e não verbalmente, para até três a cinco ações (por exemplo, restaurante, médico, bombeiro)" },
      { code: "SP12", text: "Troca brinquedos / materiais (por exemplo, participa de negociação para trocar cores de tinta durante um projeto de arte)" },
      { code: "SP13", text: "Convida pares para jogar em uma atividade preferida" },
      { code: "SP14", text: "Aborda os colegas e se junta apropriadamente na atividade em andamento" },
      { code: "SP15", text: "Aceita convite para jogar em uma atividade de escolha de colegas" },
      { code: "SP16", text: "Aceita perder jogos ou ser chamado de \"fora\"" },
      { code: "SP17", text: "Permanece envolvido apropriadamente durante horários não estruturados (por exemplo, passa para uma nova atividade depois de concluída a primeira etapa; participa de um jogo adequado à idade)" },
      { code: "SP18", text: "Segue mudanças nas ideias de jogo dos outros e sustenta as mudanças durante o jogo aberto (por exemplo, mudanças no esquema de jogo / cenário)" },
      { code: "SP19", text: "Apropriadamente joga jogos que envolvem uma pessoa sendo \"Isso\"" },
      { code: "SP20", text: "Demonstra flexibilidade em seguir as mudanças nas regras de um jogo ou em aceitar novas ideias de colegas" },
      { code: "SP21", text: "Planeja um esquema de jogo com um par e o segue (por exemplo, decide construir uma casa com blocos e depois constrói)" },
      { code: "SP22", text: "Identifica quais crianças são suas amigas e explica o porque" },
      { code: "SP23", text: "Aceita adequadamente que os gostos e interesses dos outros podem ser diferentes dos seus" },
      { code: "SP24", text: "Ganha sem se gabar" },
    ],
  },
  {
    key: "sr",
    label: "Autorregulação",
    items: [
      { code: "SR01", text: "Demonstra flexibilidade com novas atividades" },
      { code: "SR02", text: "Lida adequadamente com solicitações negadas" },
      { code: "SR03", text: "Levanta a mão e aguarda ser chamado para falar" },
      { code: "SR04", text: "Responde a estratégias calmantes utilizadas por um adulto" },
      { code: "SR05", text: "Identifica quando frustrado e apropriadamente pede uma pausa ou um item / atividade calmante" },
      { code: "SR06", text: "Segue as expectativas da sala de aula e demonstra flexibilidade durante as transições" },
      { code: "SR07", text: "Demonstra flexibilidade quando as coisas são diferentes do planejado" },
      { code: "SR08", text: "Demonstra flexibilidade quando atividades preferidas são interrompidas" },
      { code: "SR09", text: "Responde a correção sem exibir comportamentos desafiadores" },
      { code: "SR10", text: "Responde a erros cometidos por si ou por outros sem exibir comportamentos desafiadores" },
      { code: "SR11", text: "Demonstra consciência do próprio espaço e do espaço de outro (por exemplo, não pisar nos pés de outras pessoas ao caminhar em fila, não se aglomera a uma pessoa durante a hora da volta, mantendo a distância de um braço ao interagir com outras pessoas)" },
      { code: "SR12", text: "Modifica o comportamento em resposta ao feedback" },
      { code: "SR13", text: "Usa palavras apropriadas e tom de voz para recusar solicitações de outras pessoas" },
      { code: "SR14", text: "Defende a si mesmo (por exemplo, \"Eu não consegui um\". \"Não consigo ver\". \"Por favor, mude\". \"Pare\".) Sem exibir um comportamento desafiador (por exemplo, intimidação, provocações, agressão)." },
      { code: "SR15", text: "Pede ajuda durante atividades novas ou desafiadoras" },
      { code: "SR16", text: "Espera por ajuda, por um item solicitado ou quando direcionado para até um minuto sem exibir comportamentos desafiadores" },
      { code: "SR17", text: "Evita persistência em um tópico ou questão" },
      { code: "SR18", text: "Usa o nível de voz e tom de conversação ao falar" },
    ],
  },
  {
    key: "se",
    label: "Social/Emocional",
    items: [
      { code: "SE01", text: "Reconhece emoções nos outros e em si mesmo (por exemplo, feliz, triste)" },
      { code: "SE02", text: "Dá uma explicação simples para o seu próprio estado emocional e dos outros (por exemplo, feliz, triste) quando perguntado" },
      { code: "SE03", text: "Mostra empatia em relação aos outros (por exemplo, \"Você está bem?\" Para o colega que caiu no parquinho; abraça um colega que está chorando)" },
      { code: "SE04", text: "Expressa emoções negativas sem exibir comportamentos desafiadores" },
      { code: "SE05", text: "Expressa nível apropriado de entusiasmo sobre as ações ou pertences dos outros" },
      { code: "SE06", text: "Antecipa como um colega pode responder ao seu comportamento (por exemplo, derrubar uma torre pode deixar um colega furioso; ajudar um colega pode fazê-la feliz) e responde de acordo" },
    ],
  },
  {
    key: "sl",
    label: "Linguagem Social",
    items: [
      { code: "SL01", text: "Responde a saudações / despedidas" },
      { code: "SL02", text: "Segue direções envolvendo adultos nomeados ou pares" },
      { code: "SL03", text: "Inicia saudações / despedidas" },
      { code: "SL04", text: "Se dirige aos pares pelo nome" },
      { code: "SL05", text: "Responde questões sociais (por exemplo, nome, idade, nomes de família, nomes de animais de estimação)" },
      { code: "SL06", text: "Faz perguntas sociais (por exemplo, nome, idade, nomes de família, nomes de animais de estimação)" },
      { code: "SL07", text: "Faz perguntas concretas sobre um item ou informações compartilhadas por outras pessoas (por exemplo, nome do objeto, localização do objeto, quem tem algo)" },
      { code: "SL08", text: "Solicita atenção (por exemplo, \"Veja o que eu fiz\". \"Observe até onde posso pular\".)" },
      { code: "SL09", text: "Pede a atenção do ouvinte adequadamente (por exemplo, chama o nome, toca no ombro)" },
      { code: "SL10", text: "Responde a iniciações de outras pessoas" },
      { code: "SL11", text: "Responde a perguntas sobre atividades em andamento" },
      { code: "SL12", text: "Compartilha informações sobre eventos pessoais, familiares e importantes (por exemplo, dia da escola, feriados, eventos familiares)" },
      { code: "SL13", text: "Responde a mais de cinco perguntas sobre um tópico preferido" },
      { code: "SL14", text: "Faz comentários recíprocos (por exemplo, a criança responde ao colega: \"Eu também gosto desse filme!\" \"Eu não tenho (isso), eu tenho (isso)\")" },
      { code: "SL15", text: "Compartilha informações sobre passado imediato ou eventos futuros" },
      { code: "SL16", text: "Responde a perguntas, faz perguntas ou faz comentários para manter conversas de três a quatro trocas" },
      { code: "SL17", text: "Responde adequadamente quando um par muda de tópico" },
      { code: "SL18", text: "Direciona o corpo e os olhos para o parceiro social quando fala" },
      { code: "SL19", text: "Direciona o corpo e os olhos para o parceiro social ao ouvir" },
      { code: "SL20", text: "Fala com frases polidas (por exemplo, \"Por favor\", \"Obrigado\", \"Desculpe\", \"Com licença\", \"Você é bem-vindo\")" },
      { code: "SL21", text: "Aceita pessoas diferentes (por exemplo, não faz comentários negativos)" },
      { code: "SL22", text: "Procura reparar ou esclarecer as falhas nas interações sociais" },
      { code: "SL23", text: "Conversa sobre tópicos apropriados à idade (ou seja, fala sobre tópicos semelhantes e de interesse para colegas)" },
      { code: "SL24", text: "Usa linguagem contextualmente apropriada / introduz o tópico" },
    ],
  },
  {
    key: "cg",
    label: "Comportamento de Grupo/Sala de Aula",
    items: [
      { code: "CG01", text: "Segue as regras do cronograma e da sala de aula (incluindo regras do parquinho)" },
      { code: "CG02", text: "Segue instruções verbais como parte das rotinas ou atividades da sala de aula (por exemplo, pegue materiais, guardar o lanche)" },
      { code: "CG03", text: "Reconhece os próprios pertences, de outros e do grupo" },
      { code: "CG04", text: "Guarda brinquedos / materiais em locais designados" },
      { code: "CG05", text: "Responde ao professor olhando ou vindo quando solicitado direta ou indiretamente" },
      { code: "CG06", text: "Imita um colega que está liderando músicas / atividades (por exemplo, O mestre mandou)" },
      { code: "CG07", text: "Responde a dicas indiretas (por exemplo, \"Onde estão seus amigos?\" Quando a criança precisa entrar na fila)" },
      { code: "CG08", text: "Usa equipamentos de playground apropriadamente" },
      { code: "CG09", text: "Ajuda os outros, espontaneamente e quando solicitado" },
      { code: "CG10", text: "Permanece no lugar em um grupo até ser chamado pelo professor (por exemplo, permanecer sentado até ser chamado para ir para a fila)" },
      { code: "CG11", text: "Prepara-se para atividade localizando área / materiais (por exemplo, cadeira, casaco)" },
      { code: "CG12", text: "Segue as direções durante novas atividades" },
      { code: "CG13", text: "Dá direções durante novas atividades" },
      { code: "CG14", text: "Permanece no lugar ao andar em fila e mantém o ritmo com o grupo" },
      { code: "CG15", text: "Repete palavras / ações de uma música, livro ou atividade lúdica" },
      { code: "CG16", text: "Aceita que alguns pares podem seguir regras ou cronogramas diferentes" },
      { code: "CG17", text: "Solicita permissão para usar os pertences dos outros" },
      { code: "CG18", text: "Participa de atividades manuais em um grupo pequeno, conduzidas por professores, durante dez minutos" },
      { code: "CG19", text: "Senta-se em silêncio por dez minutos" },
      { code: "CG20", text: "Participa a atividade de escuta em grupo pequeno conduzida pelo professor durante dez minutos" },
      { code: "CG21", text: "Responde em conjunto com o grupo à atividade liderada pelo professor ou colega" },
      { code: "CG22", text: "Segue instruções verbais básicas de dois a três passos em um grupo" },
      { code: "CG23", text: "Passa itens para os colegas (por exemplo, distribuir materiais, revezar-se para ver um objeto compartilhado e passar para a próxima pessoa)" },
    ],
  },
  {
    key: "nv",
    label: "Linguagem Social Não-Verbal",
    items: [
      { code: "NV1", text: "Retribui as interações não-verbais (por exemplo, high five, onda, legal, cumprimento com punho, sorriso)" },
      { code: "NV2", text: "Inicia interações não-verbais (por exemplo, high five, onda, polegar para cima- legal-, cumprimento com punho, sorriso) com adultos e colegas apropriados" },
      { code: "NV3", text: "Identifica ações básicas sem palavras (por exemplo, Charadas)" },
      { code: "NV4", text: "Demonstra um nível apropriado de afeto com base na história, no relacionamento e na familiaridade com a pessoa (por exemplo, abraça o pai, faz high five com amigo, não inicia com uma pessoa desconhecida" },
      { code: "NV5", text: "Segue gestos básicos e sinais não-verbais (por exemplo, para quando a pessoa levanta a mão, vem quando uma pessoa acena com uma mão)" },
      { code: "NV6", text: "Modificado próprio comportamento baseado na linguagem corporal, ações ou olhar dos outros" },
    ],
  },
];
