/**
 * Template genérico: currículo de intervenção precoce por níveis e domínios
 * (estrutura tipo Denver/ESDM).
 *
 * A ESTRUTURA (4 níveis por faixa etária × domínios de desenvolvimento,
 * escala de 3 pontos) segue descrições públicas do modelo. O TEXTO de cada
 * item é ORIGINAL, escrito para esta aplicação — nenhum item foi copiado ou
 * parafraseado do ESDM Curriculum Checklist (Guilford/Lidel) nem de suas
 * traduções. Não usar a marca como nome de produto.
 *
 * Fontes da estrutura:
 * - https://en.wikipedia.org/wiki/Early_Start_Denver_Model
 * - https://acervodigital.ufpr.br/xmlui/handle/1884/97961
 */
import type { ProtocolTemplate } from "./types";

export const esdmTemplate: ProtocolTemplate = {
  name: "esdm",
  displayName:
    "Currículo de intervenção precoce (estrutura tipo Denver/ESDM, genérico)",
  version: "1.0",
  scale: {
    max: 2,
    labels: {
      0: "Ainda não",
      1: "Emergente / inconsistente",
      2: "Consistente",
    },
  },
  contentLicense: "original",
  sources: [
    "https://en.wikipedia.org/wiki/Early_Start_Denver_Model",
    "https://acervodigital.ufpr.br/xmlui/handle/1884/97961",
  ],
  notes:
    "O checklist original tem cerca de 480 itens; este template traz 8 objetivos representativos por domínio e nível. Complete com itens próprios pelo importador em massa.",
  domains: [
    // ------------------------------------------------------------------
    // Nível 1 (12-18 meses)
    // ------------------------------------------------------------------
    {
      level: "Nível 1 (12-18 meses)",
      domain: "Comunicação receptiva",
      items: [
        { code: "N1-CR-01", description: "Olha para o adulto quando ouve o próprio nome." },
        { code: "N1-CR-02", description: "Vira a cabeça em direção a um som ou voz vindo de fora do campo visual." },
        { code: "N1-CR-03", description: "Interrompe brevemente a atividade quando o adulto diz 'não' ou 'espera'." },
        { code: "N1-CR-04", description: "Olha para o brinquedo ou pessoa que o adulto aponta e nomeia." },
        { code: "N1-CR-05", description: "Estende o braço ou olha para o objeto quando o adulto pergunta 'quer?'." },
        { code: "N1-CR-06", description: "Atende a um pedido simples com gesto de apoio, como 'vem cá' ou 'me dá'." },
        { code: "N1-CR-07", description: "Reconhece o nome de 3 objetos familiares olhando ou pegando o item pedido." },
        { code: "N1-CR-08", description: "Aponta ou toca uma parte do corpo nomeada pelo adulto, como nariz ou barriga." },
      ],
    },
    {
      level: "Nível 1 (12-18 meses)",
      domain: "Comunicação expressiva",
      items: [
        { code: "N1-CE-01", description: "Vocaliza sons ou sílabas de forma espontânea durante a brincadeira com o adulto." },
        { code: "N1-CE-02", description: "Estende a mão ou puxa o adulto para pedir um objeto ou ação desejada." },
        { code: "N1-CE-03", description: "Aponta para um objeto próximo para pedir que o adulto o entregue." },
        { code: "N1-CE-04", description: "Usa gesto ou som para pedir 'mais' de um alimento ou brincadeira." },
        { code: "N1-CE-05", description: "Combina olhar com vocalização ou gesto ao fazer um pedido." },
        { code: "N1-CE-06", description: "Acena tchau, bate palmas ou faz outro gesto social após modelo do adulto." },
        { code: "N1-CE-07", description: "Vocaliza ou usa gesto para recusar um objeto ou atividade oferecida." },
        { code: "N1-CE-08", description: "Produz aproximações de 3 palavras com significado, como 'mamã', 'dá' ou 'não'." },
      ],
    },
    {
      level: "Nível 1 (12-18 meses)",
      domain: "Atenção conjunta",
      items: [
        { code: "N1-AC-01", description: "Alterna o olhar entre o brinquedo e o rosto do adulto durante uma atividade compartilhada." },
        { code: "N1-AC-02", description: "Segue com o olhar um objeto que o adulto move lentamente à sua frente." },
        { code: "N1-AC-03", description: "Olha para onde o adulto olha quando ele vira a cabeça de forma marcada." },
        { code: "N1-AC-04", description: "Segue o apontar do adulto para um objeto próximo dentro da sala." },
        { code: "N1-AC-05", description: "Mostra um objeto ao adulto erguendo-o na direção dele e olhando para seu rosto." },
        { code: "N1-AC-06", description: "Entrega um objeto ao adulto para compartilhar, sem estar pedindo ajuda." },
        { code: "N1-AC-07", description: "Aponta para algo interessante e olha para o adulto para compartilhar a descoberta." },
        { code: "N1-AC-08", description: "Responde ao 'olha!' do adulto dirigindo o olhar para o local indicado." },
      ],
    },
    {
      level: "Nível 1 (12-18 meses)",
      domain: "Habilidades sociais",
      items: [
        { code: "N1-HS-01", description: "Aceita o toque e a aproximação do adulto sem se afastar ou se incomodar." },
        { code: "N1-HS-02", description: "Sorri em resposta ao sorriso ou à voz animada do adulto." },
        { code: "N1-HS-03", description: "Mantém contato visual com o adulto por alguns segundos durante uma brincadeira social." },
        { code: "N1-HS-04", description: "Participa de brincadeiras corporais como cócegas ou 'cavalinho' mostrando prazer." },
        { code: "N1-HS-05", description: "Pede a continuação de uma brincadeira social quando o adulto faz pausa." },
        { code: "N1-HS-06", description: "Antecipa a próxima etapa de uma rotina social conhecida, como esconde-esconde." },
        { code: "N1-HS-07", description: "Responde a cumprimentos simples com olhar, sorriso ou gesto." },
        { code: "N1-HS-08", description: "Escolhe entre duas brincadeiras sociais oferecidas pelo adulto olhando ou apontando." },
      ],
    },
    {
      level: "Nível 1 (12-18 meses)",
      domain: "Imitação",
      items: [
        { code: "N1-IM-01", description: "Repete uma ação simples com objeto após modelo, como bater a colher na mesa." },
        { code: "N1-IM-02", description: "Imita ação do adulto com um brinquedo sonoro, como apertar ou chacoalhar." },
        { code: "N1-IM-03", description: "Imita movimentos grossos visíveis, como bater palmas ou levantar os braços." },
        { code: "N1-IM-04", description: "Imita sons ou vocalizações produzidos pelo adulto durante a interação." },
        { code: "N1-IM-05", description: "Imita movimentos da boca ou do rosto, como estalar a língua ou mandar beijo." },
        { code: "N1-IM-06", description: "Imita os gestos de uma música familiar quando o adulto canta e gesticula." },
        { code: "N1-IM-07", description: "Imita uma ação nova com objeto sem precisar de ajuda física." },
        { code: "N1-IM-08", description: "Imita uma sequência de duas ações com objetos apresentadas pelo adulto." },
      ],
    },
    {
      level: "Nível 1 (12-18 meses)",
      domain: "Cognição",
      items: [
        { code: "N1-CG-01", description: "Procura um brinquedo que foi coberto por um pano à sua frente." },
        { code: "N1-CG-02", description: "Segue com o olhar um objeto que cai ou rola para fora de vista." },
        { code: "N1-CG-03", description: "Coloca objetos iguais juntos quando o adulto oferece dois pares diferentes." },
        { code: "N1-CG-04", description: "Combina objetos idênticos com a figura correspondente, como um carrinho com sua foto." },
        { code: "N1-CG-05", description: "Encaixa uma peça redonda no tabuleiro de formas correspondente." },
        { code: "N1-CG-06", description: "Usa um objeto como ferramenta para alcançar outro, como puxar o pano com o brinquedo." },
        { code: "N1-CG-07", description: "Agrupa objetos de duas cores diferentes em recipientes separados." },
        { code: "N1-CG-08", description: "Escolhe entre dois objetos aquele que foi nomeado ou mostrado pelo adulto." },
      ],
    },
    {
      level: "Nível 1 (12-18 meses)",
      domain: "Brincar",
      items: [
        { code: "N1-BR-01", description: "Explora brinquedos com as mãos e a boca de forma variada, virando e apertando." },
        { code: "N1-BR-02", description: "Usa um brinquedo simples conforme sua função, como empurrar um carrinho." },
        { code: "N1-BR-03", description: "Coloca e retira objetos de um recipiente repetidamente." },
        { code: "N1-BR-04", description: "Aciona um brinquedo de causa e efeito, como apertar um botão para acender luz." },
        { code: "N1-BR-05", description: "Empilha dois ou três blocos e derruba ou reinicia a torre." },
        { code: "N1-BR-06", description: "Brinca com dois objetos combinados, como colocar a boneca no carrinho." },
        { code: "N1-BR-07", description: "Realiza uma ação de brincar sobre si mesmo, como fingir beber do copo vazio." },
        { code: "N1-BR-08", description: "Brinca de forma independente com um brinquedo por alguns minutos sem ajuda do adulto." },
      ],
    },
    {
      level: "Nível 1 (12-18 meses)",
      domain: "Motricidade fina",
      items: [
        { code: "N1-MF-01", description: "Pega objetos pequenos usando a ponta do polegar e do indicador." },
        { code: "N1-MF-02", description: "Transfere um objeto de uma mão para a outra durante a exploração." },
        { code: "N1-MF-03", description: "Solta objetos de forma intencional dentro de um recipiente com abertura larga." },
        { code: "N1-MF-04", description: "Empilha três blocos grandes sem que a torre caia." },
        { code: "N1-MF-05", description: "Encaixa argolas grandes em uma haste vertical sem ajuda física." },
        { code: "N1-MF-06", description: "Faz rabiscos no papel segurando o giz com a mão inteira." },
        { code: "N1-MF-07", description: "Vira páginas grossas de um livro de cartão, uma ou várias por vez." },
        { code: "N1-MF-08", description: "Coloca uma peça de encaixe com pino em um tabuleiro simples." },
      ],
    },
    {
      level: "Nível 1 (12-18 meses)",
      domain: "Motricidade grossa",
      items: [
        { code: "N1-MG-01", description: "Senta-se no chão sem apoio e alcança brinquedos ao redor mantendo o equilíbrio." },
        { code: "N1-MG-02", description: "Passa da posição sentada para engatinhar ou de pé com apoio de forma independente." },
        { code: "N1-MG-03", description: "Anda sem apoio por alguns metros dentro da sala." },
        { code: "N1-MG-04", description: "Abaixa-se para pegar um brinquedo do chão e retorna à posição de pé." },
        { code: "N1-MG-05", description: "Sobe em um sofá ou degrau baixo sem ajuda." },
        { code: "N1-MG-06", description: "Chuta ou empurra uma bola grande com o pé quando está em pé." },
        { code: "N1-MG-07", description: "Joga uma bola com as mãos na direção do adulto, ainda sem precisão." },
        { code: "N1-MG-08", description: "Sobe alguns degraus com apoio da mão do adulto ou do corrimão." },
      ],
    },
    {
      level: "Nível 1 (12-18 meses)",
      domain: "Comportamento",
      items: [
        { code: "N1-CP-01", description: "Permanece na área da atividade por 1 a 2 minutos com o adulto próximo." },
        { code: "N1-CP-02", description: "Aceita a troca de atividade quando o adulto apresenta um novo brinquedo." },
        { code: "N1-CP-03", description: "Acalma-se em poucos minutos com apoio do adulto após uma frustração leve." },
        { code: "N1-CP-04", description: "Senta-se na cadeira ou no chão para brincar quando convidado pelo adulto." },
        { code: "N1-CP-05", description: "Entrega o brinquedo ao adulto quando solicitado ao final da atividade." },
        { code: "N1-CP-06", description: "Tolera pequenas esperas de alguns segundos antes de receber o que deseja." },
        { code: "N1-CP-07", description: "Ajuda a guardar brinquedos em uma caixa com modelo do adulto." },
        { code: "N1-CP-08", description: "Realiza uma transição entre dois espaços da sala com condução verbal e gestual." },
      ],
    },
    {
      level: "Nível 1 (12-18 meses)",
      domain: "Independência pessoal",
      items: [
        { code: "N1-IP-01", description: "Come pedaços pequenos de alimento sólido com as mãos." },
        { code: "N1-IP-02", description: "Bebe de um copo com apoio do adulto sem derramar em excesso." },
        { code: "N1-IP-03", description: "Leva a colher à boca com ajuda, ainda que derrame parte do alimento." },
        { code: "N1-IP-04", description: "Estende braços e pernas para colaborar quando é vestido ou despido." },
        { code: "N1-IP-05", description: "Tira meias ou sapatos abertos quando o adulto os afrouxa." },
        { code: "N1-IP-06", description: "Aceita ter as mãos e o rosto limpos com pano ou lenço úmido." },
        { code: "N1-IP-07", description: "Aceita a escovação dos dentes feita pelo adulto por alguns segundos." },
        { code: "N1-IP-08", description: "Vai até o local da refeição ou do banho quando o adulto avisa a rotina." },
      ],
    },

    // ------------------------------------------------------------------
    // Nível 2 (18-24 meses)
    // ------------------------------------------------------------------
    {
      level: "Nível 2 (18-24 meses)",
      domain: "Comunicação receptiva",
      items: [
        { code: "N2-CR-01", description: "Segue instruções de um passo sem gesto de apoio, como 'senta' ou 'pega o sapato'." },
        { code: "N2-CR-02", description: "Identifica 8 ou mais objetos familiares nomeados entre várias opções." },
        { code: "N2-CR-03", description: "Aponta figuras de objetos conhecidos em um livro quando nomeadas." },
        { code: "N2-CR-04", description: "Identifica 5 partes do corpo em si mesmo ou em um boneco." },
        { code: "N2-CR-05", description: "Reconhece pessoas familiares pelo nome, olhando ou indo até elas." },
        { code: "N2-CR-06", description: "Responde a perguntas 'onde está?' procurando o objeto ou a pessoa no ambiente." },
        { code: "N2-CR-07", description: "Executa ações nomeadas com um objeto, como 'dá um beijo no urso' ou 'joga a bola'." },
        { code: "N2-CR-08", description: "Compreende 'pega e me dá' buscando um objeto em outro cômodo da casa." },
      ],
    },
    {
      level: "Nível 2 (18-24 meses)",
      domain: "Comunicação expressiva",
      items: [
        { code: "N2-CE-01", description: "Usa 10 ou mais palavras de forma espontânea em contextos apropriados." },
        { code: "N2-CE-02", description: "Nomeia objetos ou figuras familiares quando o adulto pergunta 'o que é?'." },
        { code: "N2-CE-03", description: "Pede com palavra um item desejado, em vez de apenas apontar." },
        { code: "N2-CE-04", description: "Diz 'não' ou 'acabou' para recusar ou indicar o fim de uma atividade." },
        { code: "N2-CE-05", description: "Diz o nome de pessoas familiares para chamá-las ou identificá-las." },
        { code: "N2-CE-06", description: "Cumprimenta e se despede com palavras, como 'oi' e 'tchau'." },
        { code: "N2-CE-07", description: "Imita palavras novas ditas pelo adulto durante a brincadeira." },
        { code: "N2-CE-08", description: "Combina duas palavras, como 'mais suco' ou 'papai carro'." },
      ],
    },
    {
      level: "Nível 2 (18-24 meses)",
      domain: "Habilidades sociais",
      items: [
        { code: "N2-HS-01", description: "Inicia uma brincadeira social conhecida com o adulto usando gesto ou palavra." },
        { code: "N2-HS-02", description: "Mantém uma troca de vai e volta com objetos por 3 ou mais turnos." },
        { code: "N2-HS-03", description: "Olha para o rosto do adulto para checar sua reação diante de algo novo." },
        { code: "N2-HS-04", description: "Aproxima-se de outra criança e observa sua brincadeira com interesse." },
        { code: "N2-HS-05", description: "Brinca lado a lado com outra criança com materiais semelhantes." },
        { code: "N2-HS-06", description: "Responde ao cumprimento de um adulto conhecido com palavra ou gesto." },
        { code: "N2-HS-07", description: "Imita ações de outra criança durante a brincadeira em grupo." },
        { code: "N2-HS-08", description: "Oferece um brinquedo a outra criança ou adulto de forma espontânea." },
      ],
    },
    {
      level: "Nível 2 (18-24 meses)",
      domain: "Imitação",
      items: [
        { code: "N2-IM-01", description: "Imita ações do adulto com objetos do cotidiano, como mexer a panela." },
        { code: "N2-IM-02", description: "Imita uma sequência de duas ou três ações com o mesmo objeto." },
        { code: "N2-IM-03", description: "Imita ações em que o objeto se relaciona com outro, como colocar a colher na xícara." },
        { code: "N2-IM-04", description: "Imita gestos simples de músicas infantis enquanto o adulto canta." },
        { code: "N2-IM-05", description: "Imita palavras de uma ou duas sílabas ditas pelo adulto." },
        { code: "N2-IM-06", description: "Imita ações de faz de conta, como dar comida a um boneco." },
        { code: "N2-IM-07", description: "Imita movimentos que envolvem o corpo todo, como girar ou pular." },
        { code: "N2-IM-08", description: "Imita ações vistas há alguns minutos, sem modelo imediato do adulto." },
      ],
    },
    {
      level: "Nível 2 (18-24 meses)",
      domain: "Cognição",
      items: [
        { code: "N2-CG-01", description: "Pareia figuras idênticas em um jogo de memória simples com 4 pares." },
        { code: "N2-CG-02", description: "Pareia objetos por cor quando há 3 cores diferentes disponíveis." },
        { code: "N2-CG-03", description: "Encaixa 3 formas básicas em um tabuleiro de formas correspondente." },
        { code: "N2-CG-04", description: "Separa objetos por tamanho, grandes e pequenos, em dois grupos." },
        { code: "N2-CG-05", description: "Encontra um objeto escondido sob um de dois panos após ver onde foi colocado." },
        { code: "N2-CG-06", description: "Monta um quebra-cabeça de encaixe com 3 ou 4 peças com pino." },
        { code: "N2-CG-07", description: "Combina figuras de objetos com o objeto real correspondente." },
        { code: "N2-CG-08", description: "Escolhe o objeto que falta para completar uma atividade, como a colher para comer." },
      ],
    },
    {
      level: "Nível 2 (18-24 meses)",
      domain: "Brincar",
      items: [
        { code: "N2-BR-01", description: "Combina vários objetos relacionados na brincadeira, como pratos, copos e colher." },
        { code: "N2-BR-02", description: "Realiza ações de faz de conta em um boneco, como dar comida ou pentear." },
        { code: "N2-BR-03", description: "Encadeia duas ações de faz de conta, como servir e depois dar de beber." },
        { code: "N2-BR-04", description: "Usa brinquedos de montar para construir estruturas simples, como uma fileira." },
        { code: "N2-BR-05", description: "Brinca de forma apropriada com diferentes tipos de brinquedo por vários minutos." },
        { code: "N2-BR-06", description: "Inclui o adulto na brincadeira de faz de conta, oferecendo comida ou bebida." },
        { code: "N2-BR-07", description: "Reproduz uma rotina conhecida na brincadeira, como colocar o boneco para dormir." },
        { code: "N2-BR-08", description: "Escolhe um brinquedo, brinca por alguns minutos e troca por outro de forma organizada." },
      ],
    },
    {
      level: "Nível 2 (18-24 meses)",
      domain: "Motricidade fina",
      items: [
        { code: "N2-MF-01", description: "Empilha 5 ou 6 blocos formando uma torre estável." },
        { code: "N2-MF-02", description: "Encaixa peças grandes de montar umas nas outras e separa-as." },
        { code: "N2-MF-03", description: "Desenha traços verticais ou circulares imitando o adulto." },
        { code: "N2-MF-04", description: "Segura o giz ou lápis com os dedos em vez da mão fechada." },
        { code: "N2-MF-05", description: "Enfia contas grandes em um cordão rígido ou fio grosso." },
        { code: "N2-MF-06", description: "Abre e fecha recipientes com tampa de rosca larga ou de encaixe." },
        { code: "N2-MF-07", description: "Usa uma das mãos para segurar e a outra para manipular, como abrir um pote." },
        { code: "N2-MF-08", description: "Vira páginas de um livro de papel uma de cada vez." },
      ],
    },
    {
      level: "Nível 2 (18-24 meses)",
      domain: "Motricidade grossa",
      items: [
        { code: "N2-MG-01", description: "Corre com passos curtos mantendo o equilíbrio em superfície plana." },
        { code: "N2-MG-02", description: "Sobe e desce escadas segurando o corrimão, colocando os dois pés em cada degrau." },
        { code: "N2-MG-03", description: "Chuta uma bola parada na direção do adulto sem perder o equilíbrio." },
        { code: "N2-MG-04", description: "Arremessa uma bola pequena por cima do ombro em direção a um alvo." },
        { code: "N2-MG-05", description: "Sobe em brinquedos de parque baixos e desce sem ajuda." },
        { code: "N2-MG-06", description: "Anda para trás alguns passos puxando um brinquedo com cordão." },
        { code: "N2-MG-07", description: "Pula no lugar com os dois pés saindo do chão ao mesmo tempo." },
        { code: "N2-MG-08", description: "Senta e levanta de uma cadeira pequena sem apoio das mãos." },
      ],
    },
    {
      level: "Nível 2 (18-24 meses)",
      domain: "Comportamento",
      items: [
        { code: "N2-CP-01", description: "Permanece sentado em uma atividade de mesa por 3 a 5 minutos com o adulto." },
        { code: "N2-CP-02", description: "Faz transições entre atividades com aviso verbal e pouco protesto." },
        { code: "N2-CP-03", description: "Aceita 'espera' por até 30 segundos quando o adulto sinaliza com palavra e gesto." },
        { code: "N2-CP-04", description: "Guarda os materiais usados na caixa quando o adulto avisa o fim da atividade." },
        { code: "N2-CP-05", description: "Usa palavra ou gesto para pedir ajuda em vez de chorar ou gritar." },
        { code: "N2-CP-06", description: "Aceita a divisão de um brinquedo com outra criança com mediação do adulto." },
        { code: "N2-CP-07", description: "Acompanha o adulto pela mão em ambientes externos sem se soltar." },
        { code: "N2-CP-08", description: "Senta em roda com outras crianças para uma música curta com apoio do adulto." },
      ],
    },
    {
      level: "Nível 2 (18-24 meses)",
      domain: "Independência pessoal",
      items: [
        { code: "N2-IP-01", description: "Come com colher de forma independente, com pouco derramamento." },
        { code: "N2-IP-02", description: "Bebe de um copo sem tampa segurando com as duas mãos." },
        { code: "N2-IP-03", description: "Tira o casaco desabotoado e os sapatos abertos sozinho." },
        { code: "N2-IP-04", description: "Lava as mãos com ajuda para abrir a torneira e enxaguar." },
        { code: "N2-IP-05", description: "Coloca o lixo em uma lixeira quando solicitado." },
        { code: "N2-IP-06", description: "Escova os dentes com ajuda do adulto, aceitando a escova por mais tempo." },
        { code: "N2-IP-07", description: "Leva o próprio prato ou copo até a pia ou mesa quando solicitado." },
        { code: "N2-IP-08", description: "Indica com gesto ou palavra quando a fralda está suja ou molhada." },
      ],
    },

    // ------------------------------------------------------------------
    // Nível 3 (24-36 meses)
    // ------------------------------------------------------------------
    {
      level: "Nível 3 (24-36 meses)",
      domain: "Comunicação receptiva",
      items: [
        { code: "N3-CR-01", description: "Segue instruções de dois passos relacionados, como 'pega o copo e coloca na mesa'." },
        { code: "N3-CR-02", description: "Compreende conceitos de lugar, como 'em cima', 'dentro' e 'embaixo'." },
        { code: "N3-CR-03", description: "Identifica objetos pela função, como 'qual usamos para beber?'." },
        { code: "N3-CR-04", description: "Aponta figuras de ações em livros quando o adulto pergunta 'quem está comendo?'." },
        { code: "N3-CR-05", description: "Reconhece conceitos de tamanho, como 'grande' e 'pequeno', ao escolher objetos." },
        { code: "N3-CR-06", description: "Responde a perguntas de sim ou não sobre desejos com palavra ou movimento da cabeça." },
        { code: "N3-CR-07", description: "Compreende pronomes pessoais ao ouvir 'me dá' e 'dá para ela'." },
        { code: "N3-CR-08", description: "Escuta uma história curta com figuras e aponta o que o adulto menciona." },
      ],
    },
    {
      level: "Nível 3 (24-36 meses)",
      domain: "Comunicação expressiva",
      items: [
        { code: "N3-CE-01", description: "Usa frases de duas ou três palavras para pedir, comentar e recusar." },
        { code: "N3-CE-02", description: "Nomeia ações em figuras ou no ambiente, como 'correndo' ou 'comendo'." },
        { code: "N3-CE-03", description: "Responde a perguntas 'o que é?' e 'onde está?' com palavras ou frases curtas." },
        { code: "N3-CE-04", description: "Usa palavras de posse e pronomes, como 'meu' e 'eu', na conversa." },
        { code: "N3-CE-05", description: "Faz perguntas simples com 'o quê?' e 'onde?' dirigidas ao adulto." },
        { code: "N3-CE-06", description: "Comenta espontaneamente sobre o que vê ou faz durante a brincadeira." },
        { code: "N3-CE-07", description: "Usa palavras para descrever atributos, como cor, tamanho ou quantidade." },
        { code: "N3-CE-08", description: "Canta trechos de músicas infantis conhecidas com palavras reconhecíveis." },
      ],
    },
    {
      level: "Nível 3 (24-36 meses)",
      domain: "Habilidades sociais",
      items: [
        { code: "N3-HS-01", description: "Chama um par pelo nome para iniciar interação ou brincadeira." },
        { code: "N3-HS-02", description: "Participa de jogos de correr ou perseguir com outra criança." },
        { code: "N3-HS-03", description: "Reveza a vez em um jogo simples com o adulto ou outra criança, com apoio verbal." },
        { code: "N3-HS-04", description: "Responde a pedidos de outra criança, como entregar um brinquedo solicitado." },
        { code: "N3-HS-05", description: "Imita e é imitado em brincadeiras com outra criança, mantendo o vaivém." },
        { code: "N3-HS-06", description: "Expressa afeto por pessoas familiares com abraços ou palavras." },
        { code: "N3-HS-07", description: "Reconhece emoções básicas, como feliz e triste, em rostos e figuras." },
        { code: "N3-HS-08", description: "Fica ao lado de outras crianças em uma roda ou atividade de grupo por alguns minutos." },
      ],
    },
    {
      level: "Nível 3 (24-36 meses)",
      domain: "Imitação",
      items: [
        { code: "N3-IM-01", description: "Imita sequências de três ações com objetos apresentadas de uma vez." },
        { code: "N3-IM-02", description: "Imita frases de duas ou três palavras ditas pelo adulto." },
        { code: "N3-IM-03", description: "Imita movimentos de dança e gestos de músicas com coordenação de braços e pernas." },
        { code: "N3-IM-04", description: "Imita ações de faz de conta observadas em outra criança." },
        { code: "N3-IM-05", description: "Imita movimentos finos de mãos e dedos em canções e brincadeiras." },
        { code: "N3-IM-06", description: "Reproduz uma construção simples com blocos após ver o modelo pronto." },
        { code: "N3-IM-07", description: "Imita um desenho simples, como um círculo ou uma cruz, feito pelo adulto." },
        { code: "N3-IM-08", description: "Reproduz, mais tarde, ações e falas observadas em outras pessoas." },
      ],
    },
    {
      level: "Nível 3 (24-36 meses)",
      domain: "Cognição",
      items: [
        { code: "N3-CG-01", description: "Pareia e separa objetos por forma, cor ou tamanho quando solicitado." },
        { code: "N3-CG-02", description: "Agrupa objetos por categoria, como animais e alimentos." },
        { code: "N3-CG-03", description: "Monta um quebra-cabeça de 4 a 6 peças interligadas." },
        { code: "N3-CG-04", description: "Identifica o item que não pertence ao grupo entre quatro objetos." },
        { code: "N3-CG-05", description: "Conta até 3 objetos apontando para cada um deles." },
        { code: "N3-CG-06", description: "Separa 'um' de 'muitos' quando o adulto pede a quantidade." },
        { code: "N3-CG-07", description: "Completa uma sequência simples de duas cores alternadas, como vermelho e azul." },
        { code: "N3-CG-08", description: "Lembra onde um objeto foi guardado e o busca após alguns minutos." },
      ],
    },
    {
      level: "Nível 3 (24-36 meses)",
      domain: "Brincar",
      items: [
        { code: "N3-BR-01", description: "Encadeia três ou mais ações de faz de conta em uma cena, como preparar e servir comida." },
        { code: "N3-BR-02", description: "Faz o boneco agir como agente, como fazê-lo andar ou falar." },
        { code: "N3-BR-03", description: "Usa um objeto substituto no faz de conta, como um bloco como telefone." },
        { code: "N3-BR-04", description: "Constrói com blocos estruturas reconhecíveis, como uma casa ou ponte." },
        { code: "N3-BR-05", description: "Assume um papel simples no faz de conta, como médico ou cozinheiro." },
        { code: "N3-BR-06", description: "Brinca com outra criança em uma mesma cena de faz de conta com apoio do adulto." },
        { code: "N3-BR-07", description: "Usa materiais de arte para criar e nomeia o que produziu." },
        { code: "N3-BR-08", description: "Brinca de forma independente por 10 minutos com materiais variados." },
      ],
    },
    {
      level: "Nível 3 (24-36 meses)",
      domain: "Motricidade fina",
      items: [
        { code: "N3-MF-01", description: "Empilha 8 ou mais blocos pequenos formando uma torre." },
        { code: "N3-MF-02", description: "Enfia contas médias em um cordão flexível segurando a ponta com a outra mão." },
        { code: "N3-MF-03", description: "Copia linhas verticais, horizontais e círculos após modelo." },
        { code: "N3-MF-04", description: "Faz cortes com tesoura infantil em um papel segurado pelo adulto." },
        { code: "N3-MF-05", description: "Abre e fecha zíperes grandes e botões de pressão." },
        { code: "N3-MF-06", description: "Amassa, rola e achata massinha para formar bolas e cobras." },
        { code: "N3-MF-07", description: "Monta e desmonta peças de encaixe pequenas, como blocos de plástico." },
        { code: "N3-MF-08", description: "Segura o lápis com três dedos ao desenhar ou rabiscar." },
      ],
    },
    {
      level: "Nível 3 (24-36 meses)",
      domain: "Motricidade grossa",
      items: [
        { code: "N3-MG-01", description: "Corre com fluidez, mudando de direção e parando sem cair." },
        { code: "N3-MG-02", description: "Sobe escadas alternando os pés, com apoio leve no corrimão." },
        { code: "N3-MG-03", description: "Pula para frente com os dois pés juntos por uma distância curta." },
        { code: "N3-MG-04", description: "Fica em um pé só por um ou dois segundos com apoio mínimo." },
        { code: "N3-MG-05", description: "Chuta uma bola em movimento lento na direção de um alvo." },
        { code: "N3-MG-06", description: "Pedala um triciclo ou velocípede por alguns metros." },
        { code: "N3-MG-07", description: "Pega uma bola grande lançada de perto com as duas mãos." },
        { code: "N3-MG-08", description: "Anda sobre uma linha ou trave baixa mantendo o equilíbrio por alguns passos." },
      ],
    },
    {
      level: "Nível 3 (24-36 meses)",
      domain: "Independência pessoal",
      items: [
        { code: "N3-IP-01", description: "Come com garfo e colher de forma independente durante a refeição." },
        { code: "N3-IP-02", description: "Bebe de um copo aberto com uma mão sem derramar." },
        { code: "N3-IP-03", description: "Veste peças simples como calça com elástico e camiseta com ajuda mínima." },
        { code: "N3-IP-04", description: "Lava e seca as mãos sozinho após lembrete verbal." },
        { code: "N3-IP-05", description: "Avisa que precisa usar o banheiro e senta no vaso com apoio." },
        { code: "N3-IP-06", description: "Escova os dentes com apoio do adulto para finalizar." },
        { code: "N3-IP-07", description: "Guarda os próprios pertences, como mochila e sapatos, no lugar combinado." },
        { code: "N3-IP-08", description: "Ajuda em tarefas domésticas simples, como colocar guardanapos na mesa." },
      ],
    },

    // ------------------------------------------------------------------
    // Nível 4 (36-48 meses)
    // ------------------------------------------------------------------
    {
      level: "Nível 4 (36-48 meses)",
      domain: "Comunicação receptiva",
      items: [
        { code: "N4-CR-01", description: "Segue instruções de dois ou três passos não relacionados sem apoio gestual." },
        { code: "N4-CR-02", description: "Compreende perguntas com 'quem', 'o quê', 'onde' e 'por quê' sobre situações do cotidiano." },
        { code: "N4-CR-03", description: "Entende conceitos de tempo, como 'antes', 'depois', 'primeiro' e 'por último'." },
        { code: "N4-CR-04", description: "Identifica objetos por características, como 'o que é vermelho e redondo?'." },
        { code: "N4-CR-05", description: "Compreende negativas em frases, como 'pega o que não é azul'." },
        { code: "N4-CR-06", description: "Escuta uma história curta e responde a perguntas simples sobre o que aconteceu." },
        { code: "N4-CR-07", description: "Compreende quantificadores como 'todos', 'alguns' e 'nenhum' em instruções." },
        { code: "N4-CR-08", description: "Segue instruções dadas ao grupo sem precisar de repetição individual." },
      ],
    },
    {
      level: "Nível 4 (36-48 meses)",
      domain: "Comunicação expressiva",
      items: [
        { code: "N4-CE-01", description: "Usa frases de quatro ou mais palavras com verbo e complemento." },
        { code: "N4-CE-02", description: "Faz perguntas com 'por quê?', 'quando?' e 'como?' para obter informação." },
        { code: "N4-CE-03", description: "Conta um evento recente com começo, meio e fim de forma compreensível." },
        { code: "N4-CE-04", description: "Usa tempos verbais no passado e futuro em frases espontâneas." },
        { code: "N4-CE-05", description: "Mantém um diálogo sobre um tema por três ou mais turnos com o adulto." },
        { code: "N4-CE-06", description: "Descreve a função de objetos comuns, como 'a tesoura serve para cortar'." },
        { code: "N4-CE-07", description: "Nomeia e explica emoções próprias, como 'estou bravo porque caiu'." },
        { code: "N4-CE-08", description: "Reconta uma história conhecida com apoio de figuras, incluindo os personagens principais." },
      ],
    },
    {
      level: "Nível 4 (36-48 meses)",
      domain: "Habilidades sociais",
      items: [
        { code: "N4-HS-01", description: "Convida outra criança para brincar usando palavras, sem precisar do adulto." },
        { code: "N4-HS-02", description: "Reveza a vez em jogos de tabuleiro simples sem apoio constante do adulto." },
        { code: "N4-HS-03", description: "Participa de brincadeiras cooperativas com um objetivo comum, como construir juntos." },
        { code: "N4-HS-04", description: "Negocia com palavras o uso de um brinquedo disputado, com pouca mediação." },
        { code: "N4-HS-05", description: "Oferece ajuda ou conforto a uma criança que está triste ou machucada." },
        { code: "N4-HS-06", description: "Segue as regras de um jogo em grupo explicadas pelo adulto." },
        { code: "N4-HS-07", description: "Responde a perguntas de outras crianças e mantém a conversa por alguns turnos." },
        { code: "N4-HS-08", description: "Participa de uma atividade de grupo com 4 ou mais crianças por 10 minutos." },
      ],
    },
    {
      level: "Nível 4 (36-48 meses)",
      domain: "Imitação",
      items: [
        { code: "N4-IM-01", description: "Imita sequências longas de ações em brincadeiras de faz de conta com vários passos." },
        { code: "N4-IM-02", description: "Imita frases completas e entonações ditas pelo adulto ou por personagens." },
        { code: "N4-IM-03", description: "Imita coreografias curtas de músicas com vários movimentos encadeados." },
        { code: "N4-IM-04", description: "Copia construções com blocos a partir de um modelo ou figura." },
        { code: "N4-IM-05", description: "Copia formas como quadrado e cruz e desenhos simples feitos pelo adulto." },
        { code: "N4-IM-06", description: "Imita ações de pares durante jogos de grupo, ajustando ritmo e ordem." },
        { code: "N4-IM-07", description: "Imita uma sequência de movimentos com regras, como 'siga o mestre'." },
        { code: "N4-IM-08", description: "Reproduz em brincadeiras ações e falas observadas em momentos anteriores do dia." },
      ],
    },
    {
      level: "Nível 4 (36-48 meses)",
      domain: "Cognição",
      items: [
        { code: "N4-CG-01", description: "Conta até 10 objetos apontando um por um e dizendo o total." },
        { code: "N4-CG-02", description: "Entrega a quantidade pedida de objetos, até 5, quando solicitado." },
        { code: "N4-CG-03", description: "Nomeia 6 ou mais cores e as formas círculo, quadrado e triângulo." },
        { code: "N4-CG-04", description: "Organiza figuras de uma sequência de três eventos na ordem correta." },
        { code: "N4-CG-05", description: "Compara objetos por atributos, como 'maior', 'mais pesado' e 'mais comprido'." },
        { code: "N4-CG-06", description: "Reconhece algumas letras, como as do próprio nome, e alguns números." },
        { code: "N4-CG-07", description: "Resolve um problema simples, como usar um banco para alcançar um objeto." },
        { code: "N4-CG-08", description: "Identifica semelhanças e diferenças entre duas figuras parecidas." },
      ],
    },
    {
      level: "Nível 4 (36-48 meses)",
      domain: "Brincar",
      items: [
        { code: "N4-BR-01", description: "Cria cenas de faz de conta com enredo, personagens e vários passos encadeados." },
        { code: "N4-BR-02", description: "Assume e mantém um papel em brincadeiras de faz de conta com outras crianças." },
        { code: "N4-BR-03", description: "Usa objetos imaginários no faz de conta, como fingir segurar um copo invisível." },
        { code: "N4-BR-04", description: "Planeja uma construção com blocos e diz o que vai construir antes de começar." },
        { code: "N4-BR-05", description: "Joga jogos de tabuleiro ou cartas simples respeitando as regras." },
        { code: "N4-BR-06", description: "Combina com outra criança quem faz o quê na brincadeira." },
        { code: "N4-BR-07", description: "Desenha figuras reconhecíveis, como uma pessoa com cabeça e membros." },
        { code: "N4-BR-08", description: "Brinca com outras crianças em atividades de parque, como pega-pega, por vários minutos." },
      ],
    },
    {
      level: "Nível 4 (36-48 meses)",
      domain: "Motricidade fina",
      items: [
        { code: "N4-MF-01", description: "Copia formas como cruz, quadrado e alguns traços de letras." },
        { code: "N4-MF-02", description: "Corta com tesoura seguindo uma linha reta e uma curva ampla." },
        { code: "N4-MF-03", description: "Abotoa e desabotoa botões médios do próprio casaco." },
        { code: "N4-MF-04", description: "Desenha uma pessoa com pelo menos três partes do corpo." },
        { code: "N4-MF-05", description: "Enfia contas pequenas em um fio seguindo um padrão de cores." },
        { code: "N4-MF-06", description: "Escreve algumas letras do próprio nome de forma reconhecível." },
        { code: "N4-MF-07", description: "Usa cola e materiais pequenos para fazer uma colagem simples." },
        { code: "N4-MF-08", description: "Manipula fechos de roupas e bolsas, como colchetes e velcros, sem ajuda." },
      ],
    },
    {
      level: "Nível 4 (36-48 meses)",
      domain: "Motricidade grossa",
      items: [
        { code: "N4-MG-01", description: "Desce escadas alternando os pés sem segurar no corrimão." },
        { code: "N4-MG-02", description: "Fica em um pé só por 3 a 5 segundos sem apoio." },
        { code: "N4-MG-03", description: "Pula com um pé só por alguns saltos consecutivos." },
        { code: "N4-MG-04", description: "Pega uma bola média lançada de dois metros com as mãos." },
        { code: "N4-MG-05", description: "Arremessa uma bola em direção a um alvo com alguma precisão." },
        { code: "N4-MG-06", description: "Corre desviando de obstáculos e para ao sinal do adulto." },
        { code: "N4-MG-07", description: "Galopa ou pula alternando os pés em brincadeiras de movimento." },
        { code: "N4-MG-08", description: "Sobe e desce em brinquedos de parque como escorregador e trepa-trepa sem ajuda." },
      ],
    },
    {
      level: "Nível 4 (36-48 meses)",
      domain: "Independência pessoal",
      items: [
        { code: "N4-IP-01", description: "Serve-se de alimentos com colher grande e come com garfo sem derramar." },
        { code: "N4-IP-02", description: "Veste e despe roupas com fechos simples de forma independente." },
        { code: "N4-IP-03", description: "Usa o banheiro de forma independente, incluindo abaixar e levantar a roupa." },
        { code: "N4-IP-04", description: "Lava o rosto e as mãos sozinho, sem lembrete, antes das refeições." },
        { code: "N4-IP-05", description: "Escova os dentes sozinho, com supervisão apenas para conferir." },
        { code: "N4-IP-06", description: "Calça sapatos com velcro ou fecho simples no pé certo." },
        { code: "N4-IP-07", description: "Arruma os próprios brinquedos no lugar combinado ao fim da brincadeira." },
        { code: "N4-IP-08", description: "Executa uma rotina de chegada ou saída, como pendurar a mochila e trocar o calçado." },
      ],
    },
  ],
};

export default esdmTemplate;
