/**
 * Perfil psicoeducacional — estrutura tipo PEP-R (genérico).
 *
 * A ESTRUTURA (níveis, domínios, quantidade de itens e escala de três
 * pontos) reproduz o que é descrito em fontes abertas de acesso público.
 * O TEXTO de cada item é original desta base e NÃO copia nem parafraseia o
 * manual PEP-R/PEP-3 (Pro-Ed) ou qualquer tradução.
 *
 * Fonte da estrutura:
 * - https://pepsic.bvsalud.org/scielo.php?script=sci_arttext&pid=S1677-04712004000100005
 */
import type { ProtocolTemplate } from "./types";

const DEV = "Escala de desenvolvimento";
const COMP = "Escala de comportamento";

export const pepRTemplate: ProtocolTemplate = {
  name: "pep_r",
  displayName: "Perfil psicoeducacional (estrutura tipo PEP-R, genérico)",
  version: "1.0",
  scale: {
    max: 2,
    labels: { 0: "Reprovado", 1: "Emergente", 2: "Aprovado" },
  },
  contentLicense: "original",
  sources: [
    "https://pepsic.bvsalud.org/scielo.php?script=sci_arttext&pid=S1677-04712004000100005",
  ],
  notes:
    "Escala de desenvolvimento: 2 = realiza a tarefa (aprovado), 1 = realiza parcialmente ou com apoio (emergente), 0 = não realiza (reprovado). Escala de comportamento: os itens descrevem comportamentos observados na sessão; 2 = apropriado, 1 = levemente inapropriado, 0 = severamente inapropriado. Itens de texto original; a estrutura segue descrições publicadas em fontes abertas.",
  domains: [
    {
      level: DEV,
      domain: "Imitação",
      items: [
        { code: "DES-IMI-01", description: "Repete um som vocal simples produzido pelo examinador logo após ouvi-lo." },
        { code: "DES-IMI-02", description: "Reproduz uma palavra curta dita pelo examinador de forma reconhecível." },
        { code: "DES-IMI-03", description: "Imita bater palmas depois de observar o examinador fazê-lo." },
        { code: "DES-IMI-04", description: "Imita movimento de bater com a mão na mesa em ritmo simples." },
        { code: "DES-IMI-05", description: "Reproduz uma sequência de dois gestos manuais na ordem apresentada." },
        { code: "DES-IMI-06", description: "Imita ação com objeto, como empurrar um carrinho depois de ver o modelo." },
        { code: "DES-IMI-07", description: "Imita sequência de duas ações com objetos diferentes." },
        { code: "DES-IMI-08", description: "Reproduz som de animal ou onomatopeia apresentada pelo examinador." },
        { code: "DES-IMI-09", description: "Imita movimento de tocar partes do próprio corpo indicadas pelo modelo." },
        { code: "DES-IMI-10", description: "Repete uma frase de três a quatro palavras dita pelo examinador." },
        { code: "DES-IMI-11", description: "Imita ritmo com instrumento de percussão simples, mantendo a cadência." },
        { code: "DES-IMI-12", description: "Copia traço vertical após demonstração com giz ou lápis." },
        { code: "DES-IMI-13", description: "Copia traço horizontal e círculo após demonstração." },
        { code: "DES-IMI-14", description: "Imita expressão facial simples, como sorrir ou franzir o rosto." },
        { code: "DES-IMI-15", description: "Imita construção de torre com blocos após ver o examinador montar." },
        { code: "DES-IMI-16", description: "Repete uma série de três números ou sílabas na ordem apresentada." },
      ],
    },
    {
      level: DEV,
      domain: "Percepção",
      items: [
        { code: "DES-PER-01", description: "Vira a cabeça em direção a um som produzido fora do campo visual." },
        { code: "DES-PER-02", description: "Acompanha com os olhos um objeto em movimento lento na horizontal." },
        { code: "DES-PER-03", description: "Reage a um estímulo visual chamativo, como luz ou objeto colorido." },
        { code: "DES-PER-04", description: "Localiza um objeto escondido sob um pano enquanto observa a ação." },
        { code: "DES-PER-05", description: "Encontra objeto pequeno deslocado entre dois recipientes." },
        { code: "DES-PER-06", description: "Reage ao próprio nome chamado em tom normal de voz." },
        { code: "DES-PER-07", description: "Toca ou explora textura apresentada sem retirar a mão de imediato." },
        { code: "DES-PER-08", description: "Identifica pelo tato objeto familiar sem vê-lo, dentro de um saco." },
        { code: "DES-PER-09", description: "Reage a cheiro forte, aproximando ou afastando o rosto." },
        { code: "DES-PER-10", description: "Distingue som suave de som forte, respondendo de modo diferente." },
        { code: "DES-PER-11", description: "Aponta para figura nomeada entre três opções." },
        { code: "DES-PER-12", description: "Percebe diferença de tamanho entre dois objetos iguais em forma." },
        { code: "DES-PER-13", description: "Indica de onde vem um som repetido dentro da sala." },
      ],
    },
    {
      level: DEV,
      domain: "Motricidade fina",
      items: [
        { code: "DES-MFI-01", description: "Segura um objeto pequeno com toda a mão quando oferecido." },
        { code: "DES-MFI-02", description: "Pega um objeto miúdo usando polegar e indicador em pinça." },
        { code: "DES-MFI-03", description: "Transfere objeto de uma mão para a outra sem deixá-lo cair." },
        { code: "DES-MFI-04", description: "Tira e coloca tampa de um pote com rosca larga." },
        { code: "DES-MFI-05", description: "Encaixa três peças em tabuleiro de formas simples." },
        { code: "DES-MFI-06", description: "Enfia contas grandes em cordão com ponta rígida." },
        { code: "DES-MFI-07", description: "Vira páginas de um livro de uma em uma." },
        { code: "DES-MFI-08", description: "Amassa e solta massa de modelar com as duas mãos." },
        { code: "DES-MFI-09", description: "Segura lápis com preensão funcional para rabiscar." },
        { code: "DES-MFI-10", description: "Recorta papel com tesoura escolar produzindo cortes curtos." },
        { code: "DES-MFI-11", description: "Recorta ao longo de uma linha reta com desvio pequeno." },
        { code: "DES-MFI-12", description: "Abotoa botão médio em peça de roupa ou tabuleiro de treino." },
        { code: "DES-MFI-13", description: "Faz bolinhas pequenas com papel ou massa usando os dedos." },
        { code: "DES-MFI-14", description: "Despeja água de uma jarra pequena em copo sem derramar muito." },
        { code: "DES-MFI-15", description: "Monta torre de oito ou mais blocos sem derrubar." },
        { code: "DES-MFI-16", description: "Toca cada dedo com o polegar da mesma mão, em sequência." },
      ],
    },
    {
      level: DEV,
      domain: "Motricidade ampla",
      items: [
        { code: "DES-MAM-01", description: "Fica em pé sem apoio por alguns segundos." },
        { code: "DES-MAM-02", description: "Caminha pela sala com passos coordenados sem apoio." },
        { code: "DES-MAM-03", description: "Corre por um trajeto curto sem cair." },
        { code: "DES-MAM-04", description: "Sobe degraus alternando os pés, com ou sem apoio no corrimão." },
        { code: "DES-MAM-05", description: "Desce degraus alternando os pés." },
        { code: "DES-MAM-06", description: "Chuta uma bola parada na direção do examinador." },
        { code: "DES-MAM-07", description: "Arremessa bola com as duas mãos por cima da cabeça." },
        { code: "DES-MAM-08", description: "Recebe uma bola grande lançada de curta distância." },
        { code: "DES-MAM-09", description: "Salta com os dois pés juntos saindo do chão." },
        { code: "DES-MAM-10", description: "Salta de um degrau baixo caindo com os dois pés." },
        { code: "DES-MAM-11", description: "Fica em um pé só por pelo menos três segundos." },
        { code: "DES-MAM-12", description: "Anda sobre uma linha no chão mantendo o equilíbrio." },
        { code: "DES-MAM-13", description: "Pula em um pé só por duas ou mais vezes seguidas." },
        { code: "DES-MAM-14", description: "Transfere-se de sentado para em pé sem usar as mãos." },
        { code: "DES-MAM-15", description: "Anda para trás por alguns passos sem perder o equilíbrio." },
        { code: "DES-MAM-16", description: "Bebe de um copo aberto levando-o à boca de forma coordenada." },
        { code: "DES-MAM-17", description: "Pedala triciclo ou empurra brinquedo de montar com os pés." },
        { code: "DES-MAM-18", description: "Passa por baixo de uma corda ou mesa sem tocá-la." },
      ],
    },
    {
      level: DEV,
      domain: "Integração olho-mão",
      items: [
        { code: "DES-IOM-01", description: "Coloca blocos dentro de uma caixa um a um." },
        { code: "DES-IOM-02", description: "Encaixa argolas em pino vertical na ordem que preferir." },
        { code: "DES-IOM-03", description: "Empilha três blocos formando torre estável." },
        { code: "DES-IOM-04", description: "Encaixa peça de quebra-cabeça com pino de encaixe." },
        { code: "DES-IOM-05", description: "Completa quebra-cabeça de três a quatro peças grandes." },
        { code: "DES-IOM-06", description: "Rabisca espontaneamente em folha de papel." },
        { code: "DES-IOM-07", description: "Copia círculo de forma fechada e reconhecível." },
        { code: "DES-IOM-08", description: "Copia quadrado com quatro lados e cantos." },
        { code: "DES-IOM-09", description: "Copia triângulo com três lados unidos." },
        { code: "DES-IOM-10", description: "Pinta dentro de uma figura grande com poucos escapes." },
        { code: "DES-IOM-11", description: "Desenha figura humana com pelo menos três partes." },
        { code: "DES-IOM-12", description: "Copia o próprio nome ou letras isoladas de um modelo." },
        { code: "DES-IOM-13", description: "Traça linha ligando dois pontos distantes na folha." },
        { code: "DES-IOM-14", description: "Reproduz modelo de blocos com quatro peças em arranjo simples." },
        { code: "DES-IOM-15", description: "Alinha objetos em fila seguindo um modelo visual." },
      ],
    },
    {
      level: DEV,
      domain: "Desempenho cognitivo",
      items: [
        { code: "DES-COG-01", description: "Combina objetos idênticos colocando cada um junto do seu par." },
        { code: "DES-COG-02", description: "Combina objeto com figura correspondente." },
        { code: "DES-COG-03", description: "Combina figuras idênticas em cartões." },
        { code: "DES-COG-04", description: "Separa objetos por cor em dois grupos." },
        { code: "DES-COG-05", description: "Separa objetos por forma em dois grupos." },
        { code: "DES-COG-06", description: "Separa objetos por tamanho, grande e pequeno." },
        { code: "DES-COG-07", description: "Aponta a figura correspondente à palavra ouvida." },
        { code: "DES-COG-08", description: "Aponta partes do corpo em si mesmo quando nomeadas." },
        { code: "DES-COG-09", description: "Aponta partes do corpo em boneco quando nomeadas." },
        { code: "DES-COG-10", description: "Segue instrução simples de uma ação com objeto." },
        { code: "DES-COG-11", description: "Segue instrução de duas ações encadeadas." },
        { code: "DES-COG-12", description: "Identifica cores nomeadas entre quatro opções." },
        { code: "DES-COG-13", description: "Identifica formas geométricas nomeadas." },
        { code: "DES-COG-14", description: "Conta objetos até três com correspondência um a um." },
        { code: "DES-COG-15", description: "Conta objetos até dez com correspondência um a um." },
        { code: "DES-COG-16", description: "Entrega a quantidade de objetos solicitada até cinco." },
        { code: "DES-COG-17", description: "Identifica numerais escritos de um a cinco." },
        { code: "DES-COG-18", description: "Identifica letras do próprio nome quando apresentadas." },
        { code: "DES-COG-19", description: "Combina letra maiúscula com a minúscula correspondente." },
        { code: "DES-COG-20", description: "Aponta o objeto que não pertence a um grupo de quatro." },
        { code: "DES-COG-21", description: "Ordena três figuras de uma sequência de ações cotidianas." },
        { code: "DES-COG-22", description: "Indica função de objetos comuns quando questionado." },
        { code: "DES-COG-23", description: "Reconhece palavras escritas familiares associadas a figuras." },
        { code: "DES-COG-24", description: "Lembra objeto retirado de um conjunto de três após ocultação." },
        { code: "DES-COG-25", description: "Completa padrão simples de cores alternadas com contas." },
        { code: "DES-COG-26", description: "Identifica o maior e o menor de três objetos." },
      ],
    },
    {
      level: DEV,
      domain: "Cognição verbal",
      items: [
        { code: "DES-CVE-01", description: "Vocaliza sons com intenção comunicativa dirigida ao adulto." },
        { code: "DES-CVE-02", description: "Usa palavras isoladas para nomear objetos familiares." },
        { code: "DES-CVE-03", description: "Nomeia figuras de objetos comuns em cartões." },
        { code: "DES-CVE-04", description: "Nomeia partes do corpo apontadas pelo examinador." },
        { code: "DES-CVE-05", description: "Nomeia cores de objetos apresentados." },
        { code: "DES-CVE-06", description: "Nomeia formas geométricas básicas." },
        { code: "DES-CVE-07", description: "Nomeia ações mostradas em figuras usando verbos." },
        { code: "DES-CVE-08", description: "Combina duas palavras para formar frase curta espontânea." },
        { code: "DES-CVE-09", description: "Usa frases de três ou mais palavras para pedir algo." },
        { code: "DES-CVE-10", description: "Responde a perguntas de sim ou não de forma coerente." },
        { code: "DES-CVE-11", description: "Responde a perguntas com 'o que' sobre objetos ou figuras." },
        { code: "DES-CVE-12", description: "Responde a perguntas com 'onde' indicando lugar." },
        { code: "DES-CVE-13", description: "Responde a perguntas com 'quem' identificando pessoa." },
        { code: "DES-CVE-14", description: "Diz o próprio nome quando perguntado." },
        { code: "DES-CVE-15", description: "Diz a própria idade ou mostra nos dedos ao ser perguntado." },
        { code: "DES-CVE-16", description: "Usa pronomes pessoais como eu, você, ele de forma adequada." },
        { code: "DES-CVE-17", description: "Usa plural ao se referir a mais de um objeto." },
        { code: "DES-CVE-18", description: "Conta números de um a dez em sequência oral." },
        { code: "DES-CVE-19", description: "Lê letras isoladas em voz alta." },
        { code: "DES-CVE-20", description: "Lê palavras curtas em voz alta." },
        { code: "DES-CVE-21", description: "Lê frase curta e responde a uma pergunta sobre ela." },
        { code: "DES-CVE-22", description: "Descreve o que vê em uma figura de cena com duas ou mais ideias." },
        { code: "DES-CVE-23", description: "Explica a função de objetos, como para que serve uma colher." },
        { code: "DES-CVE-24", description: "Reconta parte de uma história curta que acabou de ouvir." },
        { code: "DES-CVE-25", description: "Segue instrução com preposições como dentro, em cima e embaixo." },
        { code: "DES-CVE-26", description: "Completa frase com palavra que rima ou palavra oposta." },
        { code: "DES-CVE-27", description: "Faz perguntas ao examinador para obter informação." },
      ],
    },
    {
      level: COMP,
      domain: "Relacionamento e afeto",
      items: [
        { code: "COMP-REL-01", description: "Contato visual com o examinador durante interações e trocas de turno." },
        { code: "COMP-REL-02", description: "Resposta ao ser chamado pelo nome ou abordado pelo adulto." },
        { code: "COMP-REL-03", description: "Aceitação de toque físico leve, como ajuda na mão para uma tarefa." },
        { code: "COMP-REL-04", description: "Iniciativa de interação, aproximando-se ou mostrando objetos ao adulto." },
        { code: "COMP-REL-05", description: "Reação a elogios e incentivos verbais do examinador." },
        { code: "COMP-REL-06", description: "Expressão facial condizente com a situação vivida na sessão." },
        { code: "COMP-REL-07", description: "Cooperação com pedidos e instruções ao longo da avaliação." },
        { code: "COMP-REL-08", description: "Tolerância a mudanças de tarefa propostas pelo examinador." },
        { code: "COMP-REL-09", description: "Regulação emocional diante de frustração ou dificuldade em uma tarefa." },
        { code: "COMP-REL-10", description: "Reação à separação ou à presença do cuidador na sala." },
        { code: "COMP-REL-11", description: "Compartilhamento de atenção, olhando para o objeto e para o adulto." },
        { code: "COMP-REL-12", description: "Nível de atividade e permanência sentado durante as tarefas de mesa." },
      ],
    },
    {
      level: COMP,
      domain: "Brincar e interesse por materiais",
      items: [
        { code: "COMP-BRI-01", description: "Interesse inicial pelos materiais apresentados na mesa." },
        { code: "COMP-BRI-02", description: "Uso funcional dos brinquedos conforme sua finalidade." },
        { code: "COMP-BRI-03", description: "Exploração variada dos objetos em vez de ações repetitivas." },
        { code: "COMP-BRI-04", description: "Brincadeira simbólica com bonecos, carrinhos ou utensílios em miniatura." },
        { code: "COMP-BRI-05", description: "Persistência na atividade até concluir ou até ser orientado a parar." },
        { code: "COMP-BRI-06", description: "Aceitação de trocar de brinquedo quando solicitado." },
        { code: "COMP-BRI-07", description: "Uso de materiais de forma segura, sem jogar ou levar à boca." },
        { code: "COMP-BRI-08", description: "Envolvimento em brincadeira compartilhada com o examinador." },
      ],
    },
    {
      level: COMP,
      domain: "Respostas sensoriais",
      items: [
        { code: "COMP-SEN-01", description: "Reação a sons inesperados do ambiente, como porta ou telefone." },
        { code: "COMP-SEN-02", description: "Reação a sons produzidos por brinquedos musicais ou sonoros." },
        { code: "COMP-SEN-03", description: "Resposta a estímulos visuais, como luzes e objetos brilhantes." },
        { code: "COMP-SEN-04", description: "Olhar prolongado ou de canto para objetos em movimento." },
        { code: "COMP-SEN-05", description: "Reação ao toque de texturas diversas, como massa ou tecido." },
        { code: "COMP-SEN-06", description: "Reação a cheiros e sabores apresentados durante a sessão." },
        { code: "COMP-SEN-07", description: "Busca de estímulo pela boca, levando objetos não comestíveis à boca." },
        { code: "COMP-SEN-08", description: "Busca de movimento, como balançar-se ou girar durante a sessão." },
        { code: "COMP-SEN-09", description: "Uso das mãos para explorar objetos, sem cheirá-los ou lambê-los." },
        { code: "COMP-SEN-10", description: "Reação à dor ou a pequenos machucados, condizente com o estímulo." },
        { code: "COMP-SEN-11", description: "Tolerância a ruído de fundo constante da sala." },
        { code: "COMP-SEN-12", description: "Fixação em partes dos objetos, como rodas ou detalhes brilhantes." },
      ],
    },
    {
      level: COMP,
      domain: "Linguagem",
      items: [
        { code: "COMP-LIN-01", description: "Uso comunicativo da fala, dirigida ao interlocutor." },
        { code: "COMP-LIN-02", description: "Repetição imediata de frases ouvidas em vez de resposta própria." },
        { code: "COMP-LIN-03", description: "Repetição tardia de falas de desenhos, propagandas ou conversas." },
        { code: "COMP-LIN-04", description: "Entonação e ritmo da fala adequados ao contexto." },
        { code: "COMP-LIN-05", description: "Volume da voz condizente com a situação de conversa." },
        { code: "COMP-LIN-06", description: "Uso de gestos, como apontar, para complementar a comunicação." },
        { code: "COMP-LIN-07", description: "Uso correto de pronomes ao falar de si e dos outros." },
        { code: "COMP-LIN-08", description: "Resposta a perguntas simples de forma relacionada ao que foi perguntado." },
        { code: "COMP-LIN-09", description: "Vocalizações sem função comunicativa, como sons repetitivos." },
        { code: "COMP-LIN-10", description: "Compreensão de instruções verbais simples sem apoio de gesto." },
        { code: "COMP-LIN-11", description: "Manutenção de um tópico de conversa por duas ou mais trocas." },
      ],
    },
  ],
};

export default pepRTemplate;
